import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      // The React Compiler ruleset flags every "sync fetched/async data into
      // local state via useEffect" as a hard error, including idiomatic,
      // legitimate cases this project relies on throughout (react-hook-form
      // defaults reset from server data, one-time async status checks on
      // mount). Where a cleaner alternative existed (e.g. key-based remount)
      // it was used instead; downgraded to a warning rather than disabled so
      // remaining cases stay visible without blocking the build.
      "react-hooks/set-state-in-effect": "warn",
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by @ducanh2912/next-pwa on every build — not source.
    "public/sw.js",
    "public/swe-worker-*.js",
    "public/workbox-*.js",
    "public/worker-*.js",
  ]),
]);

export default eslintConfig;
